#!/usr/bin/bash

# node src/main.js

# front end based off of
# https://css-tricks.com/reactive-uis-vanillajs-part-1-pure-functional-style/

cat <<- EOF
    init: node src/main.js
    structure:
    {
        venue:          [venue name],
        venueUrl:       [venue main url],
        title:          [event title],
        description:    [event description],
        url:            [event url],
        time:           [event start time],
        date:           [event date]
    }
    venues:
        ◉ IPA
        ◉ Radio Room
        ◉ Gottrocks
        ◉ GroundZero
        ◉ Smileys

EOF
