#!/usr/bin/bash

# vue-webpack
`npm run dev`

# node, request, fb-graph
# scrub data sources && update mongodb
`node src/scripts/main.js`

# requires keys file to be present in project root folder
cat <<- EOF
{
	"mlab": "mlab_URI",
	"fb": "fb_key"
}
EOF

cat <<- EOF
    Schema Structure:
    {
        collection:     [mongo collection name],
        venue:          [venue name],
        venueUrl:       [venue main url],
        title:          [event title],
        description:    [event description],
        url:            [event url],
        time:           [event start time],
        date:           [event date],
        datetime:       [event datetime]
    }

    Routes:
        greenvilletonight.com/api/events            # all events in db
        greenvilletonight.com/api/thisweek          # this week's events
        greenvilletonight.com/api/tonight           # tonights events
        greenvilletonight.com/api/events/{venue}
        greenvilletonight.com/api/events/{venue}/{startdate}/{enddate}

    Example:
        greenvilletonight.com/api/events/other
        greenvilletonight.com/api/events/radioroom/3030-06-02/3031-07-09

    Venues:
        ◉ other
        ◉ gottrocks
        ◉ groundzero
        ◉ radioroom
        ◉ smileys
        ◉ village
EOF
