#!/usr/bin/bash

# node src/scripts/main.js

# front end based off of
# https://css-tricks.com/reactive-uis-vanillajs-part-1-pure-functional-style/

cat <<- EOF
    structure:
    {
        collection:     [mongo collection name]
        venue:          [venue name],
        venueUrl:       [venue main url],
        title:          [event title],
        description:    [event description],
        url:            [event url],
        time:           [event start time],
        date:           [event date]
    }

    Routes:
        greenvilletonight.com/api/events            # all events in db
        greenvilletonight.com/api/thisweek          # this week's events
        greenvilletonight.com/api/events/{venue}
        greenvilletonight.com/api/events/{venue}/{startdate}/{enddate}

    Example:
        greenvilletonight.com/api/events/other
        greenvilletonight.com/api/events/radioroom/3030-06-02/3031-07-09

    Venues:
        ◉ other
        ◉ gottrocks
        ◉ groundzero
        ◉ radioroom
        ◉ smileys
        ◉ village
EOF
